Foroffer/Models/ViewModels/SlideViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Foroffer.Models.ViewModels
{
    public class SlideViewModel
    {
        public Image Image { get; set; }
        public IFormFile imageFile { get; set; }
        public IEnumerable<Image> Images { get; set; }
        public Post Post { get; set; }
        public IEnumerable<Post> Posts { get; set; }
        public IEnumerable<Company> Companies { get; set; }
    }
}

Foroffer/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Foroffer.Models;
using Foroffer.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Foroffer.Controllers
{
    public class SlidesController : Controller
    {
        private readonly ForofferDbContext _offerDbContext;
        private readonly IHostingEnvironment _hostenv;
        private readonly SignInManager<AppUser> _signInManager;

        public SlidesController(ForofferDbContext offerDbContext, IHostingEnvironment hostenv, SignInManager<AppUser> signInManager)
        {
            _offerDbContext = offerDbContext;
            _hostenv = hostenv;
            _signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> Slide()
        {
            SlideViewModel svmodel = new SlideViewModel();
            svmodel.Images = await _offerDbContext.Images.ToListAsync();
            if(_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                return View(svmodel);
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Slide(IFormFile file, Image myimage)
        {
            if(file == null || file.Length == 0)
            {
                Content("No file chosen");
                return View();
            }

            string slidePath = Path.Combine(_hostenv.WebRootPath, "images", Path.GetFileName(file.FileName));

            using (var stream = new FileStream(slidePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            myimage.Path = file.FileName;
            _offerDbContext.Images.Add(myimage);
            await _offerDbContext.SaveChangesAsync();
            SlideViewModel svmodel = new SlideViewModel();
            svmodel.Images = await _offerDbContext.Images.ToListAsync();
            return RedirectToAction(nameof(Slide));
        }

        [HttpGet]
        public async Task<IActionResult> EditSlide(int Id)
        {
            SlideViewModel slideViewModel = new SlideViewModel();
            slideViewModel.Image = await _offerDbContext.Images.SingleOrDefaultAsync(x => x.Id == Id);
            return View(slideViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSlide(int Id, Image newimage, IFormFile file)
        {
            if(Id != newimage.Id)
            {
                Content("Invalid Id");
            }

            SlideViewModel slideViewModel = new SlideViewModel();
            slideViewModel.Image = await _offerDbContext.Images.SingleOrDefaultAsync(x => x.Id == Id);

            if(slideViewModel.Image != null)
            {
                if (file == null || file.Length == 0)
                {
                    Content("No file chosen");
                    return View();
                }

                string slidePath = Path.Combine(_hostenv.WebRootPath, "images", Path.GetFileName(file.FileName));

                using (var stream = new FileStream(slidePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                newimage.Path = file.FileName;
                slideViewModel.Image.Path = newimage.Path;
                await _offerDbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Slide));
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSlide(int Id)
        {
            SlideViewModel svmodel = new SlideViewModel();
            svmodel.Image = await _offerDbContext.Images.SingleOrDefaultAsync(x => x.Id == Id);
            return View(svmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteSlide(int Id, Image currentimage)
        {
            SlideViewModel svmodel = new SlideViewModel();
            svmodel.Image = await _offerDbContext.Images.SingleOrDefaultAsync(x => x.Id == Id);

            currentimage = svmodel.Image;
            _offerDbContext.Images.Remove(currentimage);
           await _offerDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Slide));
        }
    }
}

Foroffer/Views/Slides/DeleteSlide.cshtml
@model Foroffer.Models.ViewModels.SlideViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h6 style="font-weight:bold">Delete Category</h6>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="DeleteSlide" asp-controller="Slides">
                    <div class="Confirm">
                        <h6>Are you sure to delete @Model.Image.Path ?</h6>
                        <button class="choice">Yes</button>
                        <button class="choice"><a href="https://localhost:44311/Slides/Slide">No</a></button>
                    </div>
                </form>
                <br>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>

</section>

Foroffer/Views/Slides/EditSlide.cshtml
@model Foroffer.Models.ViewModels.SlideViewModel

@{
    Layout = "AdminLayout";
}

<div class="slides">
    <form method="post" asp-action="EditSlide" asp-controller="Slides" enctype="multipart/form-data">
        <input type="hidden" asp-for="Image.Id" />
        <label asp-for="imageFile.FileName">Image</label>
        <input asp-for="imageFile.FileName" class="forupload" type="file" name="file" /><br>
        <input type="submit" value="Submit" />
    </form>
</div>

Foroffer/Views/Slides/Slide.cshtml
@model Foroffer.Models.ViewModels.SlideViewModel

@{
    Layout = "AdminLayout";
}

<div class="slides">
    <form method="post" asp-action="Slide" asp-controller="Slides" enctype="multipart/form-data">
        <label asp-for="imageFile.FileName">Image</label>
        <input asp-for="imageFile.FileName" class="forupload" type="file" name="file" /><br>
        <input type="submit" value="Submit" />
    </form>
</div>

<div class="simages">
    <ul>
        @foreach (Image item in Model.Images)
        {
            <li>@item.Path <a asp-action="EditSlide" asp-controller="Slides" asp-route-id="@item.Id">Edit</a> <a asp-action="DeleteSlide" asp-controller="Slides" asp-route-id="@item.Id">Delete</a></li>

        }
    </ul>
</div>

@section Script{
    <script>
        var password;
        var clue = "Az963258741";
        password = prompt('Please, enter password to view', ' ');
        if (password == clue)
        {
            alert('Correct');
        }
        else {
            window.location = "https://kampaniyalar.com/Admin/Banned";
        }
    </script>
}