Foroffer/Models/Detailed.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Foroffer.Models
{
    public class Detailed
    {
        public Detailed()
        {
            Features = new HashSet<Feature>();
            Pictures = new HashSet<Picture>();
        }

        public int Id { get; set; }
        public ICollection<Picture> Pictures { get; set; }
        public string Outline { get; set; }
        public string CompanyInfo { get; set; }
        public ICollection<Feature> Features { get; set; }
        public Post Post { get; set; }
        public int PostId { get; set; }
        public int ViewCount { get; set; }
    }
}

Foroffer/Models/ViewModels/DetailedViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Foroffer.Models.ViewModels
{
    public class DetailedViewModel
    {
        public int Id { get; set; }
        public Post Post { get; set; }
        public IEnumerable<Post> Posts { get; set; }
        public Detailed Detailed { get; set; }
        public IEnumerable<Detailed> Detaileds { get; set; }
        public IEnumerable<IFormFile> formFiles { get; set; }
        public IFormFile File { get; set; }
        public Feature Feature { get; set; }
        public IEnumerable<Feature> Features { get; set; }
        public Picture Picture { get; set; }
        public IEnumerable<Picture> Pictures { get; set; }
        public Company Company { get; set; }
        public IEnumerable<Company> Companies { get; set; }
    }
}

Foroffer/Controllers/DetailedController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Foroffer.Models;
using Foroffer.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace Foroffer.Controllers
{
    public class DetailedController : Controller
    {
        private readonly ForofferDbContext _offerDbContext;
        private readonly IHostingEnvironment _hostenv;
        private readonly IStringLocalizer<DetailedController> _localizer;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private static bool _edited;

        public DetailedController(ForofferDbContext offerDbContext, IHostingEnvironment hostenv, IStringLocalizer<DetailedController> localizer, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _offerDbContext = offerDbContext;
            _signInManager = signInManager;
            _userManager = userManager;
            _hostenv = hostenv;
            _localizer = localizer;
        }

        public async Task<IActionResult> Detailed(int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.Where(x => x.PostId == Id).SingleOrDefaultAsync();
            dvmodel.Post = await _offerDbContext.Posts.SingleOrDefaultAsync(y => y.Id == Id);
            dvmodel.Detailed.Pictures = await _offerDbContext.Pictures.Where(e => e.Detailed.PostId == Id).ToListAsync();
            dvmodel.Detailed.Features = await _offerDbContext.Features.Where(f => f.Detailed.PostId == Id).ToListAsync();
            dvmodel.Companies = await _offerDbContext.Companies.ToListAsync();
            dvmodel.Company = await _offerDbContext.Companies.LastOrDefaultAsync();
            dvmodel.Detailed.Outline = dvmodel.Detailed.Outline.Replace(System.Environment.NewLine, "<br/>");
            if(dvmodel.Detailed.CompanyInfo != null)
            {
                dvmodel.Detailed.CompanyInfo = dvmodel.Detailed.CompanyInfo.Replace(System.Environment.NewLine, "<br/>");
            }
            
            if(dvmodel.Company.About != null)
            {
                dvmodel.Company.About = dvmodel.Company.About.Replace(System.Environment.NewLine, "<br/>");
            }

            if(dvmodel.Post.Company.Address != null)
            {
                dvmodel.Post.Company.Address = dvmodel.Post.Company.Address.Replace(System.Environment.NewLine, "<br/>");
            }

            if(dvmodel.Post.Company.MoreLink != null)
            {
                dvmodel.Post.Company.MoreLink = dvmodel.Post.Company.MoreLink.Replace(System.Environment.NewLine, "<br/>");
            }

            ViewData["Category"] = _localizer["Kateqoriyalar"];
            dvmodel.Detailed.ViewCount++;
            await _offerDbContext.SaveChangesAsync();
            return View(dvmodel);
        }

        public async Task<IActionResult> DetailedList()
        {
            AppUser currentuser = await _userManager.GetUserAsync(HttpContext.User);

            DetailedViewModel dvmodel = new DetailedViewModel();
            if(_signInManager.IsSignedIn(User) && User.IsInRole("Partner"))
            {
                dvmodel.Detaileds = await _offerDbContext.Detaileds.Where(x => x.Post.CompanyId == currentuser.CompanyId).ToListAsync();
            }
            else if(_signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                dvmodel.Detaileds = await _offerDbContext.Detaileds.ToListAsync();
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            }

            dvmodel.Pictures = await _offerDbContext.Pictures.ToListAsync();
            dvmodel.Features = await _offerDbContext.Features.ToListAsync();
            dvmodel.Posts = await _offerDbContext.Posts.ToListAsync();
            if(_edited == true)
            {
                ViewBag.Message = "Successfully edited";
            } 
            return View(dvmodel);
        }

        //CRUD
        //Detailed
            [HttpGet]
            public async Task<IActionResult> CreateDetailed(int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Post = await _offerDbContext.Posts.SingleOrDefaultAsync(x => x.Id == Id);
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || _signInManager.IsSignedIn(User) && User.IsInRole("Partner"))
            {
                return View(dvmodel);
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            } 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDetailed(Detailed detailed, int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Post = await _offerDbContext.Posts.SingleOrDefaultAsync(x => x.Id == Id);
            detailed.PostId = Id;
            _offerDbContext.Detaileds.Add(detailed);
            await _offerDbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Moderate));
        }
          
        [HttpGet]
        public async Task<IActionResult> Moderate()
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.OrderByDescending(a => a.Id).FirstOrDefaultAsync();
            return View(dvmodel);
        }
        
        //Picture
        [HttpGet]
        public async Task<IActionResult> AddPicture(int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.SingleOrDefaultAsync(x => x.Id == Id);
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || _signInManager.IsSignedIn(User) && User.IsInRole("Partner"))
            {
                return View(dvmodel);
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPicture(List<IFormFile> files, int Id)
        {
            if (files == null || files.Count == 0)
            {
                ModelState.AddModelError("", "No file selected");
                return View();
            }

            foreach(var file in files)
            {
                if(file.Length > 0)
                {
                    Picture picture = new Picture();
                    string filePath = Path.Combine(_hostenv.WebRootPath, "images", Path.GetFileName(file.FileName));

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }                   
                    picture.PicPath = file.FileName;
                    DetailedViewModel dvmodel = new DetailedViewModel();
                    dvmodel.Detailed = await _offerDbContext.Detaileds.SingleOrDefaultAsync(x => x.Id == Id);
                    picture.DetailedId = Id;
                    _offerDbContext.Pictures.Add(picture);
                    await _offerDbContext.SaveChangesAsync();
                }  
            }
            return RedirectToAction(nameof(GoToFeature));
        }

        //Feature
        [HttpGet]
        public async Task<IActionResult> SetFeature(int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.SingleOrDefaultAsync(x => x.Id == Id);
            dvmodel.Features = await _offerDbContext.Features.Where(a => a.DetailedId == Id).ToListAsync();

            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || _signInManager.IsSignedIn(User) && User.IsInRole("Partner"))
            {
                return View(dvmodel);
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetFeature(Feature feature, int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.SingleOrDefaultAsync(x => x.Id == Id);
            feature.DetailedId = Id;
            _offerDbContext.Features.Add(feature);
            await _offerDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(SetFeature));
        }

        [HttpGet]
        public async Task<IActionResult> GoToFeature()
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.OrderByDescending(a => a.Id).FirstOrDefaultAsync();
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || _signInManager.IsSignedIn(User) && User.IsInRole("Partner"))
            {
                return View(dvmodel);
            }
            else
            {
                return RedirectToAction(nameof(AccountController.LoginAdmin), "Account");
            }
        }

        //Edit
        [HttpGet]
        public async Task<IActionResult> EditDetailed(int Id)
        {
            DetailedViewModel dvmodel = new DetailedViewModel();
            dvmodel.Detailed = await _offerDbContext.Detaileds.SingleOrDefaultAsync(x => x.Id == Id);
            if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || _signInManager.IsSignedIn(User) && User.IsInRole("Partner"))

Foroffer/Views/Detailed/AddPicture.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">Add Images</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="AddPicture" asp-controller="Detailed" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>
                    <label asp-for="Detailed.Pictures">Upload Images</label>
                    <input type="file" id="fileupload" name="files" multiple class="form-control" />
                    <br>
                    <button class="push" id="btnupload" type="submit">Upload</button>
                </form>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

@section Script{
    <script>
        $(document).ready(function () {
            $('#btnupload').on('click', function () {
                var files = $('fileupload').prop("files");
                var fdata = new FormData();
                for (var i = 0; i < files.length; i++) {
                    fdata.append("files", files[i]);
                }
                if (files.length > 0) {
                    $.ajax({
                        type: "POST",
                        url: "/Detail/CreateDetailed?handler = images",
                        beforeSend: function (xhr) {
                            xhr.setRequestHeader("XSRF-TOKEN",
                                $('input:hidden[name="__RequestVerificationToken"]').val());
                        },
                        data: fdata,
                        contentType: false,
                        processData: false,
                        success: function (response) {
                            alert('File Uploaded Successfully.')
                        }
                    });
                }
                else {
                    alert('Please select a file.')
                }
            })
        });
    </script>
}

Foroffer/Views/Detailed/CreateDetailed.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">New Detailed</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="CreateDetailed" asp-controller="Detailed" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly"></div>
                    <label asp-for="Detailed.Outline">Outline</label><br />
                    <textarea asp-for="Detailed.Outline" rows="6" class="texbox"></textarea>
                    <br />
                    <label asp-for="Detailed.CompanyInfo">CompanyInfo</label><br />
                    <textarea asp-for="Detailed.CompanyInfo" rows="6" class="texbox"></textarea>
                    <br />
                    <button class="push" id="btnupload" type="submit">Next</button>
                </form>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

Foroffer/Views/Detailed/DeleteDetailed.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h6 style="font-weight:bold">Delete Feature</h6>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="DeleteDetailed" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="Confirm">
                        <h6>Are you sure to delete @Model.Detailed.Post.Title ?</h6>
                        <button class="choice">Yes</button>
                        <button class="choice"><a href="https://localhost:44311/Detailed/DetailedList">No</a></button>
                    </div>
                </form>
                <br>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>

</section>

Foroffer/Views/Detailed/DeleteFeature.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel
@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h6 style="font-weight:bold">Delete Feature</h6>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="DeleteFeature" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="Confirm">
                        <h6>Are you sure to delete @Model.Feature.Name ?</h6>
                        <button class="choice">Yes</button>
                        <button class="choice"><a href="https://localhost:44311/Admin/CompanyList">No</a></button>
                    </div>
                </form>
                <br>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>

</section>

Foroffer/Views/Detailed/DeletePicture.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h6 style="font-weight:bold">Delete Picture</h6>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="DeletePicture" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div class="Confirm">
                        <h6>Are you sure to delete @Model.Picture.PicPath ?</h6>
                        <button class="choice">Yes</button>
                        <button class="choice"><a href="https://localhost:44311/Detailed/GetPictures">No</a></button>
                    </div>
                </form>
                <br>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-3 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>

</section>

Foroffer/Views/Detailed/DetailedList.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <h5 style="color: white">Post Detailed Components</h5>
              <div class="detaileds" style="min-height: 390px">
                  <p class="successful">@ViewBag.Message</p> 
               <table border="1" class="complist">
                   <tr>
                       <th>Post Title</th>
                       <th>Detailed Info</th>
                       <th>Pictures</th>
                       <th>Features</th>
                       <th>Delete</th>
                       <th>New Picture</th>
                   </tr>
                   
                       @foreach (Detailed item in Model.Detaileds)
                       {
                   <tr>
                       <td>@item.Post.Title</td>
                       <td><a asp-action="EditDetailed" asp-controller="Detailed" asp-route-id="@item.Id">Edit</a></td>
                       <td><a asp-action="GetPictures" asp-controller="Detailed" asp-route-id="@item.Id">Edit</a></td>
                       <td><a asp-action="GetFeatures" asp-controller="Detailed" asp-route-id="@item.Id">Edit</a></td>
                       <td><a asp-action="DeleteDetailed" asp-controller="Detailed" asp-route-id="@item.Id">Delete</a></td>
                       <td><a asp-action="AddPicture" asp-controller="Detailed" asp-route-id="@item.Id">Add</a></td>
                   </tr>
                           
                       }
                   
               </table>
              </div>
         
        </div>
        <div class="col-lg-6 col-md-6">

        </div>
    </div>
</div>

Foroffer/Views/Detailed/EditDetailed.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">Edit Detailed</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="EditDetailed" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="Detailed.Id" />
                    <label asp-for="Detailed.Outline">Outline</label><br />
                    <textarea asp-for="Detailed.Outline" id="outline" class="texbox"></textarea>
                    <br />
                    <label asp-for="Detailed.CompanyInfo">CompanyInfo</label><br />
                    <textarea asp-for="Detailed.CompanyInfo" class="texbox"></textarea>
                    <br />
                    <button class="push" id="btnupload" type="submit">Edit</button>
                </form>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

Foroffer/Views/Detailed/EditFeature.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">Edit Feature</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="EditFeature" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <input type="hidden" asp-for="Feature.Id" />
                    <div class="fpart">
                        <div class="property">
                            <label asp-for="Feature.Name">Feature</label><br />
                            <input asp-for="Feature.Name" type="text" class="postinput" />
                        </div>
                        <div class="property">
                            <label asp-for="Feature.Parameter">Parameter</label><br />
                            <input asp-for="Feature.Parameter" type="text" class="postinput" />
                        </div>
                    </div>
                    <br />
                    <button id="boom">Submit</button>
                </form>
                <br />
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

Foroffer/Views/Detailed/EditPicture.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<div class="slides">
    <form method="post" asp-action="EditPicture" asp-controller="Detailed" enctype="multipart/form-data">
        <input type="hidden" asp-for="Picture.Id" />
        <label asp-for="File.FileName">Image</label>
        <input asp-for="File.FileName" class="forupload" type="file" name="file" /><br>
        <input type="submit" value="Submit" />
    </form>
</div>

Foroffer/Views/Detailed/GetFeatures.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">Detailed Features</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <ul>
                    @foreach (Feature item in Model.Features)
                    {
                        <li>@item.Name <a asp-action="EditFeature" asp-controller="Detailed" asp-route-id="@item.Id">Edit</a> <a asp-action="DeleteFeature" asp-controller="Detailed" asp-route-id="@item.Id">Delete</a> </li>
                    }
                </ul>

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

Foroffer/Views/Detailed/GetPictures.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">Detailed Pictures</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <ul>
                    @foreach (Picture item in Model.Pictures)
                    {
                        <li>@item.PicPath <a asp-action="EditPicture" asp-controller="Detailed" asp-route-id="@item.Id">Edit</a> <a asp-action="DeletePicture" asp-controller="Detailed" asp-route-id="@item.Id">Delete</a> </li>
                    }
                </ul>
              
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>

Foroffer/Views/Detailed/GoToFeature.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4">
            <h5>Add Features</h5>
                <a asp-action="SetFeature" asp-controller="Detailed" asp-route-id="@Model.Detailed.Id">Add features for detailed post</a>
        </div>
        <div class="col-lg-4 col-md-4">

        </div>
        <div class="col-lg-4 col-md-4">

        </div>
    </div>
</div>

Foroffer/Views/Detailed/Moderate.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4 col-md-4">
            <h5>Add Images</h5>
                <a asp-action="AddPicture" asp-controller="Detailed" asp-route-id="@Model.Detailed.Id">Add pictures for detailed post</a><br />
                <a asp-action="SetFeature" asp-controller="Detailed" asp-route-id="@Model.Detailed.Id">Add features for detailed post</a>
        </div>
        <div class="col-lg-4 col-md-4">

        </div>
        <div class="col-lg-4 col-md-4">

        </div>
    </div>
</div>

Foroffer/Views/Detailed/SetFeature.cshtml
@model Foroffer.Models.ViewModels.DetailedViewModel

@{
    Layout = "AdminLayout";
}

<section class="buttonpanel">
    <h5 style="font-weight:bold">New Detailed</h5>
</section>
<section class="posts">
    <div class="post-container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">
                <form method="post" asp-action="SetFeature" asp-controller="Detailed">
                    <div asp-validation-summary="ModelOnly"></div>
                    <div id="fcont"></div>
                    <div class="fpart">
                        @foreach (Feature item in Model.Features)
                        {
                            if (item != null)
                            {
                        <div class="newblock">
                            <p class="writing">@item.Name :</p>
                            <p class="writing">@item.Parameter</p>
                        </div>
                                
                            }
                        }
                        <div class="property">
                            <label asp-for="Feature.Name">Feature</label><br />
                            <input asp-for="Feature.Name" type="text" class="postinput" />
                        </div>
                        <div class="property">
                            <label asp-for="Feature.Parameter">Parameter</label><br />
                            <input asp-for="Feature.Parameter" type="text" class="postinput" />
                        </div>
                    </div>
                    <br />
                    <button id="boom">Submit</button>
                </form>
                <br />
                <button class="addnew"><a asp-action="Admin" asp-controller="Admin">Finish</a></button>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-12">

            </div>

        </div>
    </div>
</section>